package com.xmheart.model;

import java.util.Date;

public class xmhNav {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xmh_nav.id
     *
     * @mbg.generated Sat Sep 02 20:49:23 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xmh_nav.column_name
     *
     * @mbg.generated Sat Sep 02 20:49:23 CST 2017
     */
    private String columnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xmh_nav.title
     *
     * @mbg.generated Sat Sep 02 20:49:23 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xmh_nav.url
     *
     * @mbg.generated Sat Sep 02 20:49:23 CST 2017
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xmh_nav.publish_time
     *
     * @mbg.generated Sat Sep 02 20:49:23 CST 2017
     */
    private Date publishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xmh_nav.created_time
     *
     * @mbg.generated Sat Sep 02 20:49:23 CST 2017
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xmh_nav.updated_time
     *
     * @mbg.generated Sat Sep 02 20:49:23 CST 2017
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xmh_nav.id
     *
     * @return the value of xmh_nav.id
     *
     * @mbg.generated Sat Sep 02 20:49:23 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xmh_nav.id
     *
     * @param id the value for xmh_nav.id
     *
     * @mbg.generated Sat Sep 02 20:49:23 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xmh_nav.column_name
     *
     * @return the value of xmh_nav.column_name
     *
     * @mbg.generated Sat Sep 02 20:49:23 CST 2017
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xmh_nav.column_name
     *
     * @param columnName the value for xmh_nav.column_name
     *
     * @mbg.generated Sat Sep 02 20:49:23 CST 2017
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xmh_nav.title
     *
     * @return the value of xmh_nav.title
     *
     * @mbg.generated Sat Sep 02 20:49:23 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xmh_nav.title
     *
     * @param title the value for xmh_nav.title
     *
     * @mbg.generated Sat Sep 02 20:49:23 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xmh_nav.url
     *
     * @return the value of xmh_nav.url
     *
     * @mbg.generated Sat Sep 02 20:49:23 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xmh_nav.url
     *
     * @param url the value for xmh_nav.url
     *
     * @mbg.generated Sat Sep 02 20:49:23 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xmh_nav.publish_time
     *
     * @return the value of xmh_nav.publish_time
     *
     * @mbg.generated Sat Sep 02 20:49:23 CST 2017
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xmh_nav.publish_time
     *
     * @param publishTime the value for xmh_nav.publish_time
     *
     * @mbg.generated Sat Sep 02 20:49:23 CST 2017
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xmh_nav.created_time
     *
     * @return the value of xmh_nav.created_time
     *
     * @mbg.generated Sat Sep 02 20:49:23 CST 2017
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xmh_nav.created_time
     *
     * @param createdTime the value for xmh_nav.created_time
     *
     * @mbg.generated Sat Sep 02 20:49:23 CST 2017
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xmh_nav.updated_time
     *
     * @return the value of xmh_nav.updated_time
     *
     * @mbg.generated Sat Sep 02 20:49:23 CST 2017
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xmh_nav.updated_time
     *
     * @param updatedTime the value for xmh_nav.updated_time
     *
     * @mbg.generated Sat Sep 02 20:49:23 CST 2017
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
}