package com.xmheart.model;

public class XPWArticleWithBLOBs extends XPWArticle {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_article.brief
     * @mbg.generated  Thu Sep 21 15:20:38 CST 2017
     */
    private String brief;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_article.content
     * @mbg.generated  Thu Sep 21 15:20:38 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_article.brief
     * @return  the value of xpw_article.brief
     * @mbg.generated  Thu Sep 21 15:20:38 CST 2017
     */
    public String getBrief() {
        return brief;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_article.brief
     * @param brief  the value for xpw_article.brief
     * @mbg.generated  Thu Sep 21 15:20:38 CST 2017
     */
    public void setBrief(String brief) {
        this.brief = brief;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_article.content
     * @return  the value of xpw_article.content
     * @mbg.generated  Thu Sep 21 15:20:38 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_article.content
     * @param content  the value for xpw_article.content
     * @mbg.generated  Thu Sep 21 15:20:38 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }
}