package com.xmheart.model;

import java.util.Date;

public class XPWArticle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xpw_article.id
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xpw_article.column_id
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    private Long columnId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xpw_article.column_name
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    private String columnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xpw_article.title
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xpw_article.url
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xpw_article.img_url
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xpw_article.category
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xpw_article.file_name
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xpw_article.is_pinned
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    private Boolean isPinned;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xpw_article.tags
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xpw_article.publish_time
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    private Date publishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xpw_article.created_time
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xpw_article.updated_time
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xpw_article.id
     *
     * @return the value of xpw_article.id
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xpw_article.id
     *
     * @param id the value for xpw_article.id
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xpw_article.column_id
     *
     * @return the value of xpw_article.column_id
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    public Long getColumnId() {
        return columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xpw_article.column_id
     *
     * @param columnId the value for xpw_article.column_id
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    public void setColumnId(Long columnId) {
        this.columnId = columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xpw_article.column_name
     *
     * @return the value of xpw_article.column_name
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xpw_article.column_name
     *
     * @param columnName the value for xpw_article.column_name
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xpw_article.title
     *
     * @return the value of xpw_article.title
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xpw_article.title
     *
     * @param title the value for xpw_article.title
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xpw_article.url
     *
     * @return the value of xpw_article.url
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xpw_article.url
     *
     * @param url the value for xpw_article.url
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xpw_article.img_url
     *
     * @return the value of xpw_article.img_url
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xpw_article.img_url
     *
     * @param imgUrl the value for xpw_article.img_url
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xpw_article.category
     *
     * @return the value of xpw_article.category
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xpw_article.category
     *
     * @param category the value for xpw_article.category
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xpw_article.file_name
     *
     * @return the value of xpw_article.file_name
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xpw_article.file_name
     *
     * @param fileName the value for xpw_article.file_name
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xpw_article.is_pinned
     *
     * @return the value of xpw_article.is_pinned
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    public Boolean getIsPinned() {
        return isPinned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xpw_article.is_pinned
     *
     * @param isPinned the value for xpw_article.is_pinned
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    public void setIsPinned(Boolean isPinned) {
        this.isPinned = isPinned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xpw_article.tags
     *
     * @return the value of xpw_article.tags
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xpw_article.tags
     *
     * @param tags the value for xpw_article.tags
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    public void setTags(String tags) {
        this.tags = tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xpw_article.publish_time
     *
     * @return the value of xpw_article.publish_time
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xpw_article.publish_time
     *
     * @param publishTime the value for xpw_article.publish_time
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xpw_article.created_time
     *
     * @return the value of xpw_article.created_time
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xpw_article.created_time
     *
     * @param createdTime the value for xpw_article.created_time
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xpw_article.updated_time
     *
     * @return the value of xpw_article.updated_time
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xpw_article.updated_time
     *
     * @param updatedTime the value for xpw_article.updated_time
     *
     * @mbg.generated Mon Sep 18 07:36:33 CST 2017
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
}