package com.xmheart.model;

public class XPWDept {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_dept.id
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_dept.name
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_dept.image_url
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	private String imageUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_dept.intro
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	private String intro;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_dept.id
	 * @return  the value of xpw_dept.id
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_dept.id
	 * @param id  the value for xpw_dept.id
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_dept.name
	 * @return  the value of xpw_dept.name
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_dept.name
	 * @param name  the value for xpw_dept.name
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_dept.image_url
	 * @return  the value of xpw_dept.image_url
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	public String getImageUrl() {
		return imageUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_dept.image_url
	 * @param imageUrl  the value for xpw_dept.image_url
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_dept.intro
	 * @return  the value of xpw_dept.intro
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	public String getIntro() {
		return intro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_dept.intro
	 * @param intro  the value for xpw_dept.intro
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	public void setIntro(String intro) {
		this.intro = intro;
	}
}