package com.xmheart.model;

public class XPWDoctor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xpw_doctor.id
     *
     * @mbg.generated Thu Sep 07 18:48:01 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xpw_doctor.name
     *
     * @mbg.generated Thu Sep 07 18:48:01 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xpw_doctor.dept
     *
     * @mbg.generated Thu Sep 07 18:48:01 CST 2017
     */
    private String dept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xpw_doctor.duty
     *
     * @mbg.generated Thu Sep 07 18:48:01 CST 2017
     */
    private String duty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xpw_doctor.professional_title
     *
     * @mbg.generated Thu Sep 07 18:48:01 CST 2017
     */
    private String professionalTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xpw_doctor.grade
     *
     * @mbg.generated Thu Sep 07 18:48:01 CST 2017
     */
    private String grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xpw_doctor.url
     *
     * @mbg.generated Thu Sep 07 18:48:01 CST 2017
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xpw_doctor.image_url
     *
     * @mbg.generated Thu Sep 07 18:48:01 CST 2017
     */
    private String imageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xpw_doctor.intro
     *
     * @mbg.generated Thu Sep 07 18:48:01 CST 2017
     */
    private String intro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xpw_doctor.id
     *
     * @return the value of xpw_doctor.id
     *
     * @mbg.generated Thu Sep 07 18:48:01 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xpw_doctor.id
     *
     * @param id the value for xpw_doctor.id
     *
     * @mbg.generated Thu Sep 07 18:48:01 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xpw_doctor.name
     *
     * @return the value of xpw_doctor.name
     *
     * @mbg.generated Thu Sep 07 18:48:01 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xpw_doctor.name
     *
     * @param name the value for xpw_doctor.name
     *
     * @mbg.generated Thu Sep 07 18:48:01 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xpw_doctor.dept
     *
     * @return the value of xpw_doctor.dept
     *
     * @mbg.generated Thu Sep 07 18:48:01 CST 2017
     */
    public String getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xpw_doctor.dept
     *
     * @param dept the value for xpw_doctor.dept
     *
     * @mbg.generated Thu Sep 07 18:48:01 CST 2017
     */
    public void setDept(String dept) {
        this.dept = dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xpw_doctor.duty
     *
     * @return the value of xpw_doctor.duty
     *
     * @mbg.generated Thu Sep 07 18:48:01 CST 2017
     */
    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xpw_doctor.duty
     *
     * @param duty the value for xpw_doctor.duty
     *
     * @mbg.generated Thu Sep 07 18:48:01 CST 2017
     */
    public void setDuty(String duty) {
        this.duty = duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xpw_doctor.professional_title
     *
     * @return the value of xpw_doctor.professional_title
     *
     * @mbg.generated Thu Sep 07 18:48:01 CST 2017
     */
    public String getProfessionalTitle() {
        return professionalTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xpw_doctor.professional_title
     *
     * @param professionalTitle the value for xpw_doctor.professional_title
     *
     * @mbg.generated Thu Sep 07 18:48:01 CST 2017
     */
    public void setProfessionalTitle(String professionalTitle) {
        this.professionalTitle = professionalTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xpw_doctor.grade
     *
     * @return the value of xpw_doctor.grade
     *
     * @mbg.generated Thu Sep 07 18:48:01 CST 2017
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xpw_doctor.grade
     *
     * @param grade the value for xpw_doctor.grade
     *
     * @mbg.generated Thu Sep 07 18:48:01 CST 2017
     */
    public void setGrade(String grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xpw_doctor.url
     *
     * @return the value of xpw_doctor.url
     *
     * @mbg.generated Thu Sep 07 18:48:01 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xpw_doctor.url
     *
     * @param url the value for xpw_doctor.url
     *
     * @mbg.generated Thu Sep 07 18:48:01 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xpw_doctor.image_url
     *
     * @return the value of xpw_doctor.image_url
     *
     * @mbg.generated Thu Sep 07 18:48:01 CST 2017
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xpw_doctor.image_url
     *
     * @param imageUrl the value for xpw_doctor.image_url
     *
     * @mbg.generated Thu Sep 07 18:48:01 CST 2017
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xpw_doctor.intro
     *
     * @return the value of xpw_doctor.intro
     *
     * @mbg.generated Thu Sep 07 18:48:01 CST 2017
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xpw_doctor.intro
     *
     * @param intro the value for xpw_doctor.intro
     *
     * @mbg.generated Thu Sep 07 18:48:01 CST 2017
     */
    public void setIntro(String intro) {
        this.intro = intro;
    }
}