package com.xmheart.model;

public class XPWExpert {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_expert.id
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_expert.name
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_expert.dept
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	private String dept;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_expert.duty
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	private String duty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_expert.professional_title
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	private String professionalTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_expert.grade
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	private String grade;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_expert.url
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_expert.image_url
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	private String imageUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_expert.intro
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	private String intro;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_expert.id
	 * @return  the value of xpw_expert.id
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_expert.id
	 * @param id  the value for xpw_expert.id
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_expert.name
	 * @return  the value of xpw_expert.name
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_expert.name
	 * @param name  the value for xpw_expert.name
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_expert.dept
	 * @return  the value of xpw_expert.dept
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	public String getDept() {
		return dept;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_expert.dept
	 * @param dept  the value for xpw_expert.dept
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	public void setDept(String dept) {
		this.dept = dept;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_expert.duty
	 * @return  the value of xpw_expert.duty
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	public String getDuty() {
		return duty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_expert.duty
	 * @param duty  the value for xpw_expert.duty
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	public void setDuty(String duty) {
		this.duty = duty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_expert.professional_title
	 * @return  the value of xpw_expert.professional_title
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	public String getProfessionalTitle() {
		return professionalTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_expert.professional_title
	 * @param professionalTitle  the value for xpw_expert.professional_title
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	public void setProfessionalTitle(String professionalTitle) {
		this.professionalTitle = professionalTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_expert.grade
	 * @return  the value of xpw_expert.grade
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	public String getGrade() {
		return grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_expert.grade
	 * @param grade  the value for xpw_expert.grade
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	public void setGrade(String grade) {
		this.grade = grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_expert.url
	 * @return  the value of xpw_expert.url
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_expert.url
	 * @param url  the value for xpw_expert.url
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_expert.image_url
	 * @return  the value of xpw_expert.image_url
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	public String getImageUrl() {
		return imageUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_expert.image_url
	 * @param imageUrl  the value for xpw_expert.image_url
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_expert.intro
	 * @return  the value of xpw_expert.intro
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	public String getIntro() {
		return intro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_expert.intro
	 * @param intro  the value for xpw_expert.intro
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	public void setIntro(String intro) {
		this.intro = intro;
	}
}