package com.xmheart.model;

public class XPWElecNewspaper {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_electronic_newspaper.id
     * @mbg.generated  Fri Sep 22 21:31:59 CST 2017
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_electronic_newspaper.column_id
     * @mbg.generated  Fri Sep 22 21:31:59 CST 2017
     */
    private Long columnId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_electronic_newspaper.column_name
     * @mbg.generated  Fri Sep 22 21:31:59 CST 2017
     */
    private String columnName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_electronic_newspaper.title
     * @mbg.generated  Fri Sep 22 21:31:59 CST 2017
     */
    private String title;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_electronic_newspaper.years
     * @mbg.generated  Fri Sep 22 21:31:59 CST 2017
     */
    private String years;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_electronic_newspaper.times
     * @mbg.generated  Fri Sep 22 21:31:59 CST 2017
     */
    private String times;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_electronic_newspaper.url
     * @mbg.generated  Fri Sep 22 21:31:59 CST 2017
     */
    private String url;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column xpw_electronic_newspaper.content
     * @mbg.generated  Fri Sep 22 21:31:59 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_electronic_newspaper.id
     * @return  the value of xpw_electronic_newspaper.id
     * @mbg.generated  Fri Sep 22 21:31:59 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_electronic_newspaper.id
     * @param id  the value for xpw_electronic_newspaper.id
     * @mbg.generated  Fri Sep 22 21:31:59 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_electronic_newspaper.column_id
     * @return  the value of xpw_electronic_newspaper.column_id
     * @mbg.generated  Fri Sep 22 21:31:59 CST 2017
     */
    public Long getColumnId() {
        return columnId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_electronic_newspaper.column_id
     * @param columnId  the value for xpw_electronic_newspaper.column_id
     * @mbg.generated  Fri Sep 22 21:31:59 CST 2017
     */
    public void setColumnId(Long columnId) {
        this.columnId = columnId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_electronic_newspaper.column_name
     * @return  the value of xpw_electronic_newspaper.column_name
     * @mbg.generated  Fri Sep 22 21:31:59 CST 2017
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_electronic_newspaper.column_name
     * @param columnName  the value for xpw_electronic_newspaper.column_name
     * @mbg.generated  Fri Sep 22 21:31:59 CST 2017
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_electronic_newspaper.title
     * @return  the value of xpw_electronic_newspaper.title
     * @mbg.generated  Fri Sep 22 21:31:59 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_electronic_newspaper.title
     * @param title  the value for xpw_electronic_newspaper.title
     * @mbg.generated  Fri Sep 22 21:31:59 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_electronic_newspaper.years
     * @return  the value of xpw_electronic_newspaper.years
     * @mbg.generated  Fri Sep 22 21:31:59 CST 2017
     */
    public String getYears() {
        return years;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_electronic_newspaper.years
     * @param years  the value for xpw_electronic_newspaper.years
     * @mbg.generated  Fri Sep 22 21:31:59 CST 2017
     */
    public void setYears(String years) {
        this.years = years;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_electronic_newspaper.times
     * @return  the value of xpw_electronic_newspaper.times
     * @mbg.generated  Fri Sep 22 21:31:59 CST 2017
     */
    public String getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_electronic_newspaper.times
     * @param times  the value for xpw_electronic_newspaper.times
     * @mbg.generated  Fri Sep 22 21:31:59 CST 2017
     */
    public void setTimes(String times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_electronic_newspaper.url
     * @return  the value of xpw_electronic_newspaper.url
     * @mbg.generated  Fri Sep 22 21:31:59 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_electronic_newspaper.url
     * @param url  the value for xpw_electronic_newspaper.url
     * @mbg.generated  Fri Sep 22 21:31:59 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column xpw_electronic_newspaper.content
     * @return  the value of xpw_electronic_newspaper.content
     * @mbg.generated  Fri Sep 22 21:31:59 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column xpw_electronic_newspaper.content
     * @param content  the value for xpw_electronic_newspaper.content
     * @mbg.generated  Fri Sep 22 21:31:59 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }
}