package com.xmheart.model;

public class XPWIndex {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xpw_index.id
     *
     * @mbg.generated Tue Oct 17 09:46:05 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xpw_index.banner_image_1_url
     *
     * @mbg.generated Tue Oct 17 09:46:05 CST 2017
     */
    private String bannerImage1Url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xpw_index.banner_image_2_url
     *
     * @mbg.generated Tue Oct 17 09:46:05 CST 2017
     */
    private String bannerImage2Url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xpw_index.banner_image_3_url
     *
     * @mbg.generated Tue Oct 17 09:46:05 CST 2017
     */
    private String bannerImage3Url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xpw_index.banner_article_1_url
     *
     * @mbg.generated Tue Oct 17 09:46:05 CST 2017
     */
    private String bannerArticle1Url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xpw_index.banner_article_1_brief
     *
     * @mbg.generated Tue Oct 17 09:46:05 CST 2017
     */
    private String bannerArticle1Brief;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xpw_index.banner_article_2_url
     *
     * @mbg.generated Tue Oct 17 09:46:05 CST 2017
     */
    private String bannerArticle2Url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xpw_index.banner_article_2_brief
     *
     * @mbg.generated Tue Oct 17 09:46:05 CST 2017
     */
    private String bannerArticle2Brief;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xpw_index.banner_article_3_url
     *
     * @mbg.generated Tue Oct 17 09:46:05 CST 2017
     */
    private String bannerArticle3Url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xpw_index.banner_article_3_brief
     *
     * @mbg.generated Tue Oct 17 09:46:05 CST 2017
     */
    private String bannerArticle3Brief;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xpw_index.id
     *
     * @return the value of xpw_index.id
     *
     * @mbg.generated Tue Oct 17 09:46:05 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xpw_index.id
     *
     * @param id the value for xpw_index.id
     *
     * @mbg.generated Tue Oct 17 09:46:05 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xpw_index.banner_image_1_url
     *
     * @return the value of xpw_index.banner_image_1_url
     *
     * @mbg.generated Tue Oct 17 09:46:05 CST 2017
     */
    public String getBannerImage1Url() {
        return bannerImage1Url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xpw_index.banner_image_1_url
     *
     * @param bannerImage1Url the value for xpw_index.banner_image_1_url
     *
     * @mbg.generated Tue Oct 17 09:46:05 CST 2017
     */
    public void setBannerImage1Url(String bannerImage1Url) {
        this.bannerImage1Url = bannerImage1Url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xpw_index.banner_image_2_url
     *
     * @return the value of xpw_index.banner_image_2_url
     *
     * @mbg.generated Tue Oct 17 09:46:05 CST 2017
     */
    public String getBannerImage2Url() {
        return bannerImage2Url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xpw_index.banner_image_2_url
     *
     * @param bannerImage2Url the value for xpw_index.banner_image_2_url
     *
     * @mbg.generated Tue Oct 17 09:46:05 CST 2017
     */
    public void setBannerImage2Url(String bannerImage2Url) {
        this.bannerImage2Url = bannerImage2Url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xpw_index.banner_image_3_url
     *
     * @return the value of xpw_index.banner_image_3_url
     *
     * @mbg.generated Tue Oct 17 09:46:05 CST 2017
     */
    public String getBannerImage3Url() {
        return bannerImage3Url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xpw_index.banner_image_3_url
     *
     * @param bannerImage3Url the value for xpw_index.banner_image_3_url
     *
     * @mbg.generated Tue Oct 17 09:46:05 CST 2017
     */
    public void setBannerImage3Url(String bannerImage3Url) {
        this.bannerImage3Url = bannerImage3Url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xpw_index.banner_article_1_url
     *
     * @return the value of xpw_index.banner_article_1_url
     *
     * @mbg.generated Tue Oct 17 09:46:05 CST 2017
     */
    public String getBannerArticle1Url() {
        return bannerArticle1Url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xpw_index.banner_article_1_url
     *
     * @param bannerArticle1Url the value for xpw_index.banner_article_1_url
     *
     * @mbg.generated Tue Oct 17 09:46:05 CST 2017
     */
    public void setBannerArticle1Url(String bannerArticle1Url) {
        this.bannerArticle1Url = bannerArticle1Url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xpw_index.banner_article_1_brief
     *
     * @return the value of xpw_index.banner_article_1_brief
     *
     * @mbg.generated Tue Oct 17 09:46:05 CST 2017
     */
    public String getBannerArticle1Brief() {
        return bannerArticle1Brief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xpw_index.banner_article_1_brief
     *
     * @param bannerArticle1Brief the value for xpw_index.banner_article_1_brief
     *
     * @mbg.generated Tue Oct 17 09:46:05 CST 2017
     */
    public void setBannerArticle1Brief(String bannerArticle1Brief) {
        this.bannerArticle1Brief = bannerArticle1Brief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xpw_index.banner_article_2_url
     *
     * @return the value of xpw_index.banner_article_2_url
     *
     * @mbg.generated Tue Oct 17 09:46:05 CST 2017
     */
    public String getBannerArticle2Url() {
        return bannerArticle2Url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xpw_index.banner_article_2_url
     *
     * @param bannerArticle2Url the value for xpw_index.banner_article_2_url
     *
     * @mbg.generated Tue Oct 17 09:46:05 CST 2017
     */
    public void setBannerArticle2Url(String bannerArticle2Url) {
        this.bannerArticle2Url = bannerArticle2Url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xpw_index.banner_article_2_brief
     *
     * @return the value of xpw_index.banner_article_2_brief
     *
     * @mbg.generated Tue Oct 17 09:46:05 CST 2017
     */
    public String getBannerArticle2Brief() {
        return bannerArticle2Brief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xpw_index.banner_article_2_brief
     *
     * @param bannerArticle2Brief the value for xpw_index.banner_article_2_brief
     *
     * @mbg.generated Tue Oct 17 09:46:05 CST 2017
     */
    public void setBannerArticle2Brief(String bannerArticle2Brief) {
        this.bannerArticle2Brief = bannerArticle2Brief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xpw_index.banner_article_3_url
     *
     * @return the value of xpw_index.banner_article_3_url
     *
     * @mbg.generated Tue Oct 17 09:46:05 CST 2017
     */
    public String getBannerArticle3Url() {
        return bannerArticle3Url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xpw_index.banner_article_3_url
     *
     * @param bannerArticle3Url the value for xpw_index.banner_article_3_url
     *
     * @mbg.generated Tue Oct 17 09:46:05 CST 2017
     */
    public void setBannerArticle3Url(String bannerArticle3Url) {
        this.bannerArticle3Url = bannerArticle3Url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xpw_index.banner_article_3_brief
     *
     * @return the value of xpw_index.banner_article_3_brief
     *
     * @mbg.generated Tue Oct 17 09:46:05 CST 2017
     */
    public String getBannerArticle3Brief() {
        return bannerArticle3Brief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xpw_index.banner_article_3_brief
     *
     * @param bannerArticle3Brief the value for xpw_index.banner_article_3_brief
     *
     * @mbg.generated Tue Oct 17 09:46:05 CST 2017
     */
    public void setBannerArticle3Brief(String bannerArticle3Brief) {
        this.bannerArticle3Brief = bannerArticle3Brief;
    }
}