package com.xmheart.mapper;

import com.xmheart.model.xmhNav;
import com.xmheart.model.xmhNavExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface xmhNavMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xmh_nav
     *
     * @mbg.generated Sat Sep 02 20:49:23 CST 2017
     */
    long countByExample(xmhNavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xmh_nav
     *
     * @mbg.generated Sat Sep 02 20:49:23 CST 2017
     */
    int deleteByExample(xmhNavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xmh_nav
     *
     * @mbg.generated Sat Sep 02 20:49:23 CST 2017
     */
    @Delete({
        "delete from xmh_nav",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xmh_nav
     *
     * @mbg.generated Sat Sep 02 20:49:23 CST 2017
     */
    @Insert({
        "insert into xmh_nav (column_name, title, ",
        "url, publish_time, ",
        "created_time, updated_time)",
        "values (#{columnName,jdbcType=VARCHAR}, #{title,jdbcType=VARCHAR}, ",
        "#{url,jdbcType=VARCHAR}, #{publishTime,jdbcType=TIMESTAMP}, ",
        "#{createdTime,jdbcType=TIMESTAMP}, #{updatedTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(xmhNav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xmh_nav
     *
     * @mbg.generated Sat Sep 02 20:49:23 CST 2017
     */
    int insertSelective(xmhNav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xmh_nav
     *
     * @mbg.generated Sat Sep 02 20:49:23 CST 2017
     */
    List<xmhNav> selectByExample(xmhNavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xmh_nav
     *
     * @mbg.generated Sat Sep 02 20:49:23 CST 2017
     */
    @Select({
        "select",
        "id, column_name, title, url, publish_time, created_time, updated_time",
        "from xmh_nav",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.xmheart.mapper.xmhNavMapper.BaseResultMap")
    xmhNav selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xmh_nav
     *
     * @mbg.generated Sat Sep 02 20:49:23 CST 2017
     */
    int updateByExampleSelective(@Param("record") xmhNav record, @Param("example") xmhNavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xmh_nav
     *
     * @mbg.generated Sat Sep 02 20:49:23 CST 2017
     */
    int updateByExample(@Param("record") xmhNav record, @Param("example") xmhNavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xmh_nav
     *
     * @mbg.generated Sat Sep 02 20:49:23 CST 2017
     */
    int updateByPrimaryKeySelective(xmhNav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xmh_nav
     *
     * @mbg.generated Sat Sep 02 20:49:23 CST 2017
     */
    @Update({
        "update xmh_nav",
        "set column_name = #{columnName,jdbcType=VARCHAR},",
          "title = #{title,jdbcType=VARCHAR},",
          "url = #{url,jdbcType=VARCHAR},",
          "publish_time = #{publishTime,jdbcType=TIMESTAMP},",
          "created_time = #{createdTime,jdbcType=TIMESTAMP},",
          "updated_time = #{updatedTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(xmhNav record);
}