package com.xmheart.mapper;

import com.xmheart.model.XPWElecNewspager;
import com.xmheart.model.XPWElecNewspagerExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface XPWElecNewspagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xpw_electronic_newspaper
     *
     * @mbg.generated Sun Sep 10 17:49:27 CST 2017
     */
    long countByExample(XPWElecNewspagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xpw_electronic_newspaper
     *
     * @mbg.generated Sun Sep 10 17:49:27 CST 2017
     */
    int deleteByExample(XPWElecNewspagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xpw_electronic_newspaper
     *
     * @mbg.generated Sun Sep 10 17:49:27 CST 2017
     */
    @Delete({
        "delete from xpw_electronic_newspaper",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xpw_electronic_newspaper
     *
     * @mbg.generated Sun Sep 10 17:49:27 CST 2017
     */
    @Insert({
        "insert into xpw_electronic_newspaper (column_id, column_name, ",
        "title, url, content)",
        "values (#{columnId,jdbcType=BIGINT}, #{columnName,jdbcType=VARCHAR}, ",
        "#{title,jdbcType=VARCHAR}, #{url,jdbcType=VARCHAR}, #{content,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(XPWElecNewspager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xpw_electronic_newspaper
     *
     * @mbg.generated Sun Sep 10 17:49:27 CST 2017
     */
    int insertSelective(XPWElecNewspager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xpw_electronic_newspaper
     *
     * @mbg.generated Sun Sep 10 17:49:27 CST 2017
     */
    List<XPWElecNewspager> selectByExample(XPWElecNewspagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xpw_electronic_newspaper
     *
     * @mbg.generated Sun Sep 10 17:49:27 CST 2017
     */
    @Select({
        "select",
        "id, column_id, column_name, title, url, content",
        "from xpw_electronic_newspaper",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.xmheart.mapper.XPWElecNewspagerMapper.BaseResultMap")
    XPWElecNewspager selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xpw_electronic_newspaper
     *
     * @mbg.generated Sun Sep 10 17:49:27 CST 2017
     */
    int updateByExampleSelective(@Param("record") XPWElecNewspager record, @Param("example") XPWElecNewspagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xpw_electronic_newspaper
     *
     * @mbg.generated Sun Sep 10 17:49:27 CST 2017
     */
    int updateByExample(@Param("record") XPWElecNewspager record, @Param("example") XPWElecNewspagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xpw_electronic_newspaper
     *
     * @mbg.generated Sun Sep 10 17:49:27 CST 2017
     */
    int updateByPrimaryKeySelective(XPWElecNewspager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xpw_electronic_newspaper
     *
     * @mbg.generated Sun Sep 10 17:49:27 CST 2017
     */
    @Update({
        "update xpw_electronic_newspaper",
        "set column_id = #{columnId,jdbcType=BIGINT},",
          "column_name = #{columnName,jdbcType=VARCHAR},",
          "title = #{title,jdbcType=VARCHAR},",
          "url = #{url,jdbcType=VARCHAR},",
          "content = #{content,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(XPWElecNewspager record);
}