package com.xmheart.mapper;

import com.xmheart.model.XPWExpert;
import com.xmheart.model.XPWExpertExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface XPWExpertMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_expert
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	long countByExample(XPWExpertExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_expert
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	int deleteByExample(XPWExpertExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_expert
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	@Delete({ "delete from xpw_expert", "where id = #{id,jdbcType=BIGINT}" })
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_expert
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	@Insert({ "insert into xpw_expert (name, dept, ", "duty, professional_title, ", "grade, url, image_url, ", "intro)",
			"values (#{name,jdbcType=VARCHAR}, #{dept,jdbcType=VARCHAR}, ",
			"#{duty,jdbcType=VARCHAR}, #{professionalTitle,jdbcType=VARCHAR}, ",
			"#{grade,jdbcType=VARCHAR}, #{url,jdbcType=VARCHAR}, #{imageUrl,jdbcType=VARCHAR}, ",
			"#{intro,jdbcType=LONGVARCHAR})" })
	@SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
	int insert(XPWExpert record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_expert
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	int insertSelective(XPWExpert record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_expert
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	List<XPWExpert> selectByExampleWithBLOBs(XPWExpertExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_expert
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	List<XPWExpert> selectByExample(XPWExpertExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_expert
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	@Select({ "select", "id, name, dept, duty, professional_title, grade, url, image_url, intro", "from xpw_expert",
			"where id = #{id,jdbcType=BIGINT}" })
	@ResultMap("com.xmheart.mapper.XPWExpertMapper.ResultMapWithBLOBs")
	XPWExpert selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_expert
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	int updateByExampleSelective(@Param("record") XPWExpert record, @Param("example") XPWExpertExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_expert
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	int updateByExampleWithBLOBs(@Param("record") XPWExpert record, @Param("example") XPWExpertExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_expert
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	int updateByExample(@Param("record") XPWExpert record, @Param("example") XPWExpertExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_expert
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	int updateByPrimaryKeySelective(XPWExpert record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_expert
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	@Update({ "update xpw_expert", "set name = #{name,jdbcType=VARCHAR},", "dept = #{dept,jdbcType=VARCHAR},",
			"duty = #{duty,jdbcType=VARCHAR},", "professional_title = #{professionalTitle,jdbcType=VARCHAR},",
			"grade = #{grade,jdbcType=VARCHAR},", "url = #{url,jdbcType=VARCHAR},",
			"image_url = #{imageUrl,jdbcType=VARCHAR},", "intro = #{intro,jdbcType=LONGVARCHAR}",
			"where id = #{id,jdbcType=BIGINT}" })
	int updateByPrimaryKeyWithBLOBs(XPWExpert record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_expert
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	@Update({ "update xpw_expert", "set name = #{name,jdbcType=VARCHAR},", "dept = #{dept,jdbcType=VARCHAR},",
			"duty = #{duty,jdbcType=VARCHAR},", "professional_title = #{professionalTitle,jdbcType=VARCHAR},",
			"grade = #{grade,jdbcType=VARCHAR},", "url = #{url,jdbcType=VARCHAR},",
			"image_url = #{imageUrl,jdbcType=VARCHAR}", "where id = #{id,jdbcType=BIGINT}" })
	int updateByPrimaryKey(XPWExpert record);
}