package com.xmheart.mapper;

import com.xmheart.model.XPWNewsMediaArticle;
import com.xmheart.model.XPWNewsMediaArticleExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import com.xmheart.model.XPWNewsMediaArticleWithBLOBs;

public interface XPWNewsMediaArticleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_news_media_article
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	long countByExample(XPWNewsMediaArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_news_media_article
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	int deleteByExample(XPWNewsMediaArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_news_media_article
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	@Delete({ "delete from xpw_news_media_article", "where id = #{id,jdbcType=BIGINT}" })
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_news_media_article
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	@Insert({ "insert into xpw_news_media_article (column_id, column_name, ", "title, url, img_url, ",
			"category, file_name, ", "is_pinned, publish_time, ", "created_time, updated_time, ", "brief, content)",
			"values (#{columnId,jdbcType=BIGINT}, #{columnName,jdbcType=VARCHAR}, ",
			"#{title,jdbcType=VARCHAR}, #{url,jdbcType=VARCHAR}, #{imgUrl,jdbcType=VARCHAR}, ",
			"#{category,jdbcType=VARCHAR}, #{fileName,jdbcType=VARCHAR}, ",
			"#{isPinned,jdbcType=TINYINT}, #{publishTime,jdbcType=TIMESTAMP}, ",
			"#{createdTime,jdbcType=TIMESTAMP}, #{updatedTime,jdbcType=TIMESTAMP}, ",
			"#{brief,jdbcType=LONGVARCHAR}, #{content,jdbcType=LONGVARCHAR})" })
	@SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
	int insert(XPWNewsMediaArticleWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_news_media_article
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	int insertSelective(XPWNewsMediaArticleWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_news_media_article
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	List<XPWNewsMediaArticleWithBLOBs> selectByExampleWithBLOBs(XPWNewsMediaArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_news_media_article
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	List<XPWNewsMediaArticle> selectByExample(XPWNewsMediaArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_news_media_article
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	@Select({ "select", "id, column_id, column_name, title, url, img_url, category, file_name, is_pinned, ",
			"publish_time, created_time, updated_time, brief, content", "from xpw_news_media_article",
			"where id = #{id,jdbcType=BIGINT}" })
	@ResultMap("com.xmheart.mapper.XPWNewsMediaArticleMapper.ResultMapWithBLOBs")
	XPWNewsMediaArticleWithBLOBs selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_news_media_article
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	int updateByExampleSelective(@Param("record") XPWNewsMediaArticleWithBLOBs record,
			@Param("example") XPWNewsMediaArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_news_media_article
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	int updateByExampleWithBLOBs(@Param("record") XPWNewsMediaArticleWithBLOBs record,
			@Param("example") XPWNewsMediaArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_news_media_article
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	int updateByExample(@Param("record") XPWNewsMediaArticle record,
			@Param("example") XPWNewsMediaArticleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_news_media_article
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	int updateByPrimaryKeySelective(XPWNewsMediaArticleWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_news_media_article
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	@Update({ "update xpw_news_media_article", "set column_id = #{columnId,jdbcType=BIGINT},",
			"column_name = #{columnName,jdbcType=VARCHAR},", "title = #{title,jdbcType=VARCHAR},",
			"url = #{url,jdbcType=VARCHAR},", "img_url = #{imgUrl,jdbcType=VARCHAR},",
			"category = #{category,jdbcType=VARCHAR},", "file_name = #{fileName,jdbcType=VARCHAR},",
			"is_pinned = #{isPinned,jdbcType=TINYINT},", "publish_time = #{publishTime,jdbcType=TIMESTAMP},",
			"created_time = #{createdTime,jdbcType=TIMESTAMP},", "updated_time = #{updatedTime,jdbcType=TIMESTAMP},",
			"brief = #{brief,jdbcType=LONGVARCHAR},", "content = #{content,jdbcType=LONGVARCHAR}",
			"where id = #{id,jdbcType=BIGINT}" })
	int updateByPrimaryKeyWithBLOBs(XPWNewsMediaArticleWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xpw_news_media_article
	 * @mbg.generated  Thu Sep 07 16:26:06 CST 2017
	 */
	@Update({ "update xpw_news_media_article", "set column_id = #{columnId,jdbcType=BIGINT},",
			"column_name = #{columnName,jdbcType=VARCHAR},", "title = #{title,jdbcType=VARCHAR},",
			"url = #{url,jdbcType=VARCHAR},", "img_url = #{imgUrl,jdbcType=VARCHAR},",
			"category = #{category,jdbcType=VARCHAR},", "file_name = #{fileName,jdbcType=VARCHAR},",
			"is_pinned = #{isPinned,jdbcType=TINYINT},", "publish_time = #{publishTime,jdbcType=TIMESTAMP},",
			"created_time = #{createdTime,jdbcType=TIMESTAMP},", "updated_time = #{updatedTime,jdbcType=TIMESTAMP}",
			"where id = #{id,jdbcType=BIGINT}" })
	int updateByPrimaryKey(XPWNewsMediaArticle record);
}