
package com.xmheart.zysoft;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-03-29T10:33:30.063+08:00
 * Generated source version: 3.2.4
 */

@WebFault(name = "CallInterfaceFault", targetNamespace = "http://www.zysoft.com/")
public class CallInterfaceFault_Exception extends Exception {

    private CallInterfaceFault callInterfaceFault;

    public CallInterfaceFault_Exception() {
        super();
    }

    public CallInterfaceFault_Exception(String message) {
        super(message);
    }

    public CallInterfaceFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public CallInterfaceFault_Exception(String message, CallInterfaceFault callInterfaceFault) {
        super(message);
        this.callInterfaceFault = callInterfaceFault;
    }

    public CallInterfaceFault_Exception(String message, CallInterfaceFault callInterfaceFault, java.lang.Throwable cause) {
        super(message, cause);
        this.callInterfaceFault = callInterfaceFault;
    }

    public CallInterfaceFault getFaultInfo() {
        return this.callInterfaceFault;
    }
}
