package com.xmheart.zysoft;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-03-29T10:33:30.104+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://www.zysoft.com/", name = "WSInterfacePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface WSInterfacePortType {

    @WebMethod(operationName = "CallInterface", action = "http://www.zysoft.com/CallInterface")
    @Action(input = "http://www.zysoft.com/CallInterface", output = "http://www.zysoft.com/WSInterfaceSoap/CallInterfaceResponse", fault = {@FaultAction(className = CallInterfaceFault_Exception.class, value = "http://www.zysoft.com//WSInterfacePortType/CallInterfaceFault")})
    @RequestWrapper(localName = "CallInterface", targetNamespace = "http://www.zysoft.com/", className = "com.xmheart.zysoft.CallInterface")
    @ResponseWrapper(localName = "CallInterfaceResponse", targetNamespace = "http://www.zysoft.com/", className = "com.xmheart.zysoft.CallInterfaceResponse")
    @WebResult(name = "CallInterfaceResult", targetNamespace = "http://www.zysoft.com/")
    public java.lang.String callInterface(
        @WebParam(name = "msgHeader", targetNamespace = "http://www.zysoft.com/")
        java.lang.String msgHeader,
        @WebParam(name = "msgBody", targetNamespace = "http://www.zysoft.com/")
        java.lang.String msgBody
    ) throws CallInterfaceFault_Exception;
}
